import Header from '@/Shared/Header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Foooter from '@/Shared/Footer/Foooter'

const inter = Inter({ subsets: ['latin'] }) 

export const metadata: Metadata = {
  title: 'Information App',
  description: 'Generated by Masud',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        {/* <Foooter/> */}
        </body>
    </html>
  )
}
